// This file contains static data for all Pokémon with their proper types
export const pokemonTypesData: {[key: number]: {name: string, types: string[]}} = {
  // Gen 1 Pokémon (1-151)
  1: { name: "Bulbasaur", types: ["Grass", "Poison"] },
  2: { name: "Ivysaur", types: ["Grass", "Poison"] },
  3: { name: "Venusaur", types: ["Grass", "Poison"] },
  4: { name: "Charmander", types: ["Fire"] },
  5: { name: "Charmeleon", types: ["Fire"] },
  6: { name: "Charizard", types: ["Fire", "Flying"] },
  7: { name: "Squirtle", types: ["Water"] },
  8: { name: "Wartortle", types: ["Water"] },
  9: { name: "Blastoise", types: ["Water"] },
  10: { name: "Caterpie", types: ["Bug"] },
  11: { name: "Metapod", types: ["Bug"] },
  12: { name: "Butterfree", types: ["Bug", "Flying"] },
  13: { name: "Weedle", types: ["Bug", "Poison"] },
  14: { name: "Kakuna", types: ["Bug", "Poison"] },
  15: { name: "Beedrill", types: ["Bug", "Poison"] },
  16: { name: "Pidgey", types: ["Normal", "Flying"] },
  17: { name: "Pidgeotto", types: ["Normal", "Flying"] },
  18: { name: "Pidgeot", types: ["Normal", "Flying"] },
  19: { name: "Rattata", types: ["Normal"] },
  20: { name: "Raticate", types: ["Normal"] },
  21: { name: "Spearow", types: ["Normal", "Flying"] },
  22: { name: "Fearow", types: ["Normal", "Flying"] },
  23: { name: "Ekans", types: ["Poison"] },
  24: { name: "Arbok", types: ["Poison"] },
  25: { name: "Pikachu", types: ["Electric"] },
  26: { name: "Raichu", types: ["Electric"] },
  27: { name: "Sandshrew", types: ["Ground"] },
  28: { name: "Sandslash", types: ["Ground"] },
  29: { name: "Nidoran♀", types: ["Poison"] },
  30: { name: "Nidorina", types: ["Poison"] },
  31: { name: "Nidoqueen", types: ["Poison", "Ground"] },
  32: { name: "Nidoran♂", types: ["Poison"] },
  33: { name: "Nidorino", types: ["Poison"] },
  34: { name: "Nidoking", types: ["Poison", "Ground"] },
  35: { name: "Clefairy", types: ["Fairy"] },
  36: { name: "Clefable", types: ["Fairy"] },
  37: { name: "Vulpix", types: ["Fire"] },
  38: { name: "Ninetales", types: ["Fire"] },
  39: { name: "Jigglypuff", types: ["Normal", "Fairy"] },
  40: { name: "Wigglytuff", types: ["Normal", "Fairy"] },
  41: { name: "Zubat", types: ["Poison", "Flying"] },
  42: { name: "Golbat", types: ["Poison", "Flying"] },
  43: { name: "Oddish", types: ["Grass", "Poison"] },
  44: { name: "Gloom", types: ["Grass", "Poison"] },
  45: { name: "Vileplume", types: ["Grass", "Poison"] },
  46: { name: "Paras", types: ["Bug", "Grass"] },
  47: { name: "Parasect", types: ["Bug", "Grass"] },
  48: { name: "Venonat", types: ["Bug", "Poison"] },
  49: { name: "Venomoth", types: ["Bug", "Poison"] },
  50: { name: "Diglett", types: ["Ground"] },
  51: { name: "Dugtrio", types: ["Ground"] },
  52: { name: "Meowth", types: ["Normal"] },
  53: { name: "Persian", types: ["Normal"] },
  54: { name: "Psyduck", types: ["Water"] },
  55: { name: "Golduck", types: ["Water"] },
  56: { name: "Mankey", types: ["Fighting"] },
  57: { name: "Primeape", types: ["Fighting"] },
  58: { name: "Growlithe", types: ["Fire"] },
  59: { name: "Arcanine", types: ["Fire"] },
  60: { name: "Poliwag", types: ["Water"] },
  61: { name: "Poliwhirl", types: ["Water"] },
  62: { name: "Poliwrath", types: ["Water", "Fighting"] },
  63: { name: "Abra", types: ["Psychic"] },
  64: { name: "Kadabra", types: ["Psychic"] },
  65: { name: "Alakazam", types: ["Psychic"] },
  66: { name: "Machop", types: ["Fighting"] },
  67: { name: "Machoke", types: ["Fighting"] },
  68: { name: "Machamp", types: ["Fighting"] },
  69: { name: "Bellsprout", types: ["Grass", "Poison"] },
  70: { name: "Weepinbell", types: ["Grass", "Poison"] },
  71: { name: "Victreebel", types: ["Grass", "Poison"] },
  72: { name: "Tentacool", types: ["Water", "Poison"] },
  73: { name: "Tentacruel", types: ["Water", "Poison"] },
  74: { name: "Geodude", types: ["Rock", "Ground"] },
  75: { name: "Graveler", types: ["Rock", "Ground"] },
  76: { name: "Golem", types: ["Rock", "Ground"] },
  77: { name: "Ponyta", types: ["Fire"] },
  78: { name: "Rapidash", types: ["Fire"] },
  79: { name: "Slowpoke", types: ["Water", "Psychic"] },
  80: { name: "Slowbro", types: ["Water", "Psychic"] },
  81: { name: "Magnemite", types: ["Electric", "Steel"] },
  82: { name: "Magneton", types: ["Electric", "Steel"] },
  83: { name: "Farfetch'd", types: ["Normal", "Flying"] },
  84: { name: "Doduo", types: ["Normal", "Flying"] },
  85: { name: "Dodrio", types: ["Normal", "Flying"] },
  86: { name: "Seel", types: ["Water"] },
  87: { name: "Dewgong", types: ["Water", "Ice"] },
  88: { name: "Grimer", types: ["Poison"] },
  89: { name: "Muk", types: ["Poison"] },
  90: { name: "Shellder", types: ["Water"] },
  91: { name: "Cloyster", types: ["Water", "Ice"] },
  92: { name: "Gastly", types: ["Ghost", "Poison"] },
  93: { name: "Haunter", types: ["Ghost", "Poison"] },
  94: { name: "Gengar", types: ["Ghost", "Poison"] },
  95: { name: "Onix", types: ["Rock", "Ground"] },
  96: { name: "Drowzee", types: ["Psychic"] },
  97: { name: "Hypno", types: ["Psychic"] },
  98: { name: "Krabby", types: ["Water"] },
  99: { name: "Kingler", types: ["Water"] },
  100: { name: "Voltorb", types: ["Electric"] },
  101: { name: "Electrode", types: ["Electric"] },
  102: { name: "Exeggcute", types: ["Grass", "Psychic"] },
  103: { name: "Exeggutor", types: ["Grass", "Psychic"] },
  104: { name: "Cubone", types: ["Ground"] },
  105: { name: "Marowak", types: ["Ground"] },
  106: { name: "Hitmonlee", types: ["Fighting"] },
  107: { name: "Hitmonchan", types: ["Fighting"] },
  108: { name: "Lickitung", types: ["Normal"] },
  109: { name: "Koffing", types: ["Poison"] },
  110: { name: "Weezing", types: ["Poison"] },
  111: { name: "Rhyhorn", types: ["Ground", "Rock"] },
  112: { name: "Rhydon", types: ["Ground", "Rock"] },
  113: { name: "Chansey", types: ["Normal"] },
  114: { name: "Tangela", types: ["Grass"] },
  115: { name: "Kangaskhan", types: ["Normal"] },
  116: { name: "Horsea", types: ["Water"] },
  117: { name: "Seadra", types: ["Water"] },
  118: { name: "Goldeen", types: ["Water"] },
  119: { name: "Seaking", types: ["Water"] },
  120: { name: "Staryu", types: ["Water"] },
  121: { name: "Starmie", types: ["Water", "Psychic"] },
  122: { name: "Mr. Mime", types: ["Psychic", "Fairy"] },
  123: { name: "Scyther", types: ["Bug", "Flying"] },
  124: { name: "Jynx", types: ["Ice", "Psychic"] },
  125: { name: "Electabuzz", types: ["Electric"] },
  126: { name: "Magmar", types: ["Fire"] },
  127: { name: "Pinsir", types: ["Bug"] },
  128: { name: "Tauros", types: ["Normal"] },
  129: { name: "Magikarp", types: ["Water"] },
  130: { name: "Gyarados", types: ["Water", "Flying"] },
  131: { name: "Lapras", types: ["Water", "Ice"] },
  132: { name: "Ditto", types: ["Normal"] },
  133: { name: "Eevee", types: ["Normal"] },
  134: { name: "Vaporeon", types: ["Water"] },
  135: { name: "Jolteon", types: ["Electric"] },
  136: { name: "Flareon", types: ["Fire"] },
  137: { name: "Porygon", types: ["Normal"] },
  138: { name: "Omanyte", types: ["Rock", "Water"] },
  139: { name: "Omastar", types: ["Rock", "Water"] },
  140: { name: "Kabuto", types: ["Rock", "Water"] },
  141: { name: "Kabutops", types: ["Rock", "Water"] },
  142: { name: "Aerodactyl", types: ["Rock", "Flying"] },
  143: { name: "Snorlax", types: ["Normal"] },
  144: { name: "Articuno", types: ["Ice", "Flying"] },
  145: { name: "Zapdos", types: ["Electric", "Flying"] },
  146: { name: "Moltres", types: ["Fire", "Flying"] },
  147: { name: "Dratini", types: ["Dragon"] },
  148: { name: "Dragonair", types: ["Dragon"] },
  149: { name: "Dragonite", types: ["Dragon", "Flying"] },
  150: { name: "Mewtwo", types: ["Psychic"] },
  151: { name: "Mew", types: ["Psychic"] },

  // Gen 2 Pokémon (152-251)
  152: { name: "Chikorita", types: ["Grass"] },
  153: { name: "Bayleef", types: ["Grass"] },
  154: { name: "Meganium", types: ["Grass"] },
  155: { name: "Cyndaquil", types: ["Fire"] },
  156: { name: "Quilava", types: ["Fire"] },
  157: { name: "Typhlosion", types: ["Fire"] },
  158: { name: "Totodile", types: ["Water"] },
  159: { name: "Croconaw", types: ["Water"] },
  160: { name: "Feraligatr", types: ["Water"] },
  196: { name: "Espeon", types: ["Psychic"] },
  197: { name: "Umbreon", types: ["Dark"] },
  243: { name: "Raikou", types: ["Electric"] },
  244: { name: "Entei", types: ["Fire"] },
  245: { name: "Suicune", types: ["Water"] },
  249: { name: "Lugia", types: ["Psychic", "Flying"] },
  250: { name: "Ho-Oh", types: ["Fire", "Flying"] },
  251: { name: "Celebi", types: ["Psychic", "Grass"] },

  // Gen 3 Pokémon (252-386)
  252: { name: "Treecko", types: ["Grass"] },
  253: { name: "Grovyle", types: ["Grass"] },
  254: { name: "Sceptile", types: ["Grass"] },
  255: { name: "Torchic", types: ["Fire"] },
  256: { name: "Combusken", types: ["Fire", "Fighting"] },
  257: { name: "Blaziken", types: ["Fire", "Fighting"] },
  258: { name: "Mudkip", types: ["Water"] },
  259: { name: "Marshtomp", types: ["Water", "Ground"] },
  260: { name: "Swampert", types: ["Water", "Ground"] },
  350: { name: "Milotic", types: ["Water"] },
  383: { name: "Groudon", types: ["Ground"] },
  384: { name: "Rayquaza", types: ["Dragon", "Flying"] },
  385: { name: "Jirachi", types: ["Steel", "Psychic"] },
  386: { name: "Deoxys", types: ["Psychic"] },

  // Gen 4 Pokémon (387-493)
  387: { name: "Turtwig", types: ["Grass"] },
  388: { name: "Grotle", types: ["Grass"] },
  389: { name: "Torterra", types: ["Grass", "Ground"] },
  390: { name: "Chimchar", types: ["Fire"] },
  391: { name: "Monferno", types: ["Fire", "Fighting"] },
  392: { name: "Infernape", types: ["Fire", "Fighting"] },
  393: { name: "Piplup", types: ["Water"] },
  394: { name: "Prinplup", types: ["Water"] },
  395: { name: "Empoleon", types: ["Water", "Steel"] },
  470: { name: "Leafeon", types: ["Grass"] },
  471: { name: "Glaceon", types: ["Ice"] },
  493: { name: "Arceus", types: ["Normal"] },

  // Gen 5 Pokémon (494-649)
  495: { name: "Snivy", types: ["Grass"] },
  496: { name: "Servine", types: ["Grass"] },
  497: { name: "Serperior", types: ["Grass"] },
  498: { name: "Tepig", types: ["Fire"] },
  499: { name: "Pignite", types: ["Fire", "Fighting"] },
  500: { name: "Emboar", types: ["Fire", "Fighting"] },
  501: { name: "Oshawott", types: ["Water"] },
  502: { name: "Dewott", types: ["Water"] },
  503: { name: "Samurott", types: ["Water"] },
  643: { name: "Reshiram", types: ["Dragon", "Fire"] },
  644: { name: "Zekrom", types: ["Dragon", "Electric"] },
  646: { name: "Kyurem", types: ["Dragon", "Ice"] },

  // Gen 6 Pokémon (650-721)
  650: { name: "Chespin", types: ["Grass"] },
  651: { name: "Quilladin", types: ["Grass"] },
  652: { name: "Chesnaught", types: ["Grass", "Fighting"] },
  653: { name: "Fennekin", types: ["Fire"] },
  654: { name: "Braixen", types: ["Fire"] },
  655: { name: "Delphox", types: ["Fire", "Psychic"] },
  656: { name: "Froakie", types: ["Water"] },
  657: { name: "Frogadier", types: ["Water"] },
  658: { name: "Greninja", types: ["Water", "Dark"] },
  700: { name: "Sylveon", types: ["Fairy"] },
  716: { name: "Xerneas", types: ["Fairy"] },
  717: { name: "Yveltal", types: ["Dark", "Flying"] },

  // Gen 7 Pokémon (722-809)
  722: { name: "Rowlet", types: ["Grass", "Flying"] },
  723: { name: "Dartrix", types: ["Grass", "Flying"] },
  724: { name: "Decidueye", types: ["Grass", "Ghost"] },
  725: { name: "Litten", types: ["Fire"] },
  726: { name: "Torracat", types: ["Fire"] },
  727: { name: "Incineroar", types: ["Fire", "Dark"] },
  728: { name: "Popplio", types: ["Water"] },
  729: { name: "Brionne", types: ["Water"] },
  730: { name: "Primarina", types: ["Water", "Fairy"] },
  800: { name: "Necrozma", types: ["Psychic"] },
  802: { name: "Marshadow", types: ["Fighting", "Ghost"] },

  // Gen 8 Pokémon (810-905)
  810: { name: "Grookey", types: ["Grass"] },
  811: { name: "Thwackey", types: ["Grass"] },
  812: { name: "Rillaboom", types: ["Grass"] },
  813: { name: "Scorbunny", types: ["Fire"] },
  814: { name: "Raboot", types: ["Fire"] },
  815: { name: "Cinderace", types: ["Fire"] },
  816: { name: "Sobble", types: ["Water"] },
  817: { name: "Drizzile", types: ["Water"] },
  818: { name: "Inteleon", types: ["Water"] },
  888: { name: "Zacian", types: ["Fairy"] },
  889: { name: "Zamazenta", types: ["Fighting"] },
  890: { name: "Eternatus", types: ["Poison", "Dragon"] },

  // Gen 9 Pokémon (906-1025)
  906: { name: "Sprigatito", types: ["Grass"] },
  907: { name: "Floragato", types: ["Grass"] },
  908: { name: "Meowscarada", types: ["Grass", "Dark"] },
  909: { name: "Fuecoco", types: ["Fire"] },
  910: { name: "Crocalor", types: ["Fire"] },
  911: { name: "Skeledirge", types: ["Fire", "Ghost"] },
  912: { name: "Quaxly", types: ["Water"] },
  913: { name: "Quaxwell", types: ["Water"] },
  914: { name: "Quaquaval", types: ["Water", "Fighting"] },
  1000: { name: "Gholdengo", types: ["Steel", "Ghost"] },
  1010: { name: "Iron Valiant", types: ["Fairy", "Fighting"] }
};